steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --dockerfile=/Dockerfile.realmd
    - --destination=gcr.io/$PROJECT_ID/mangos-realmd:latest
    - --cache=true
    - --cache-ttl=12h
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --dockerfile=/Dockerfile.mangosd
    - --destination=gcr.io/$PROJECT_ID/mangos-mangosd:latest
    - --cache=true
    - --cache-ttl=12h
options:
  machineType: 'N1_HIGHCPU_8'
timeout: "45m"
